format = """
$directory\
$fill\
$git_branch\
$git_commit\
$git_state\
$git_status\
$fill\
$battery\
$time\
$all\
$cmd_duration\
$sudo\
$character\
"""

[directory]
home_symbol = "  "
truncation_length = 2
truncation_symbol = " "
read_only = "  "
use_os_path_sep = true
style = "italic blue"
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_style = 'bold blue'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) [  ](bold bright-blue)'

[fill]
symbol = ' '

[git_branch]
format = " [$branch(:$remote_branch)]($style)"
symbol = "[  ](bold italic bright-blue)"
style = "italic bright-blue"
truncation_symbol = "⋯"
truncation_length = 4
ignore_branches = ["main", "master"]
only_attached = true

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[git_status]
style = "bold italic bright-blue"
format = "([⎪$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed⎥]($style))"
conflicted = "[ 󱚟 ](italic bright-magenta)"
ahead = "[ │[${count}](bold white)│](italic green)"
behind = "[ │[${count}](bold white)│](italic red)"
diverged = "[󱡷  ┤[${ahead_count}](regular white)│ ┤[${behind_count}](regular white)│](italic bright-magenta)"
untracked = "[◌◦](italic bright-yellow)"
stashed = "[◃◈](italic white)"
modified = "[●◦](italic yellow)"
staged = "[ ┤[$count](bold white)│](italic bright-cyan)"
renamed = "[◎◦](italic bright-blue)"
deleted = "[](italic red)"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "󰁹"
charging_symbol = "[↑](italic bold green)"
discharging_symbol = "↓"
unknown_symbol = " "
empty_symbol = "󰂃"

[[battery.display]]
threshold = 20
style = "italic #ff0000"

[[battery.display]]
threshold = 30
style = "italic #ff9500"

[[battery.display]]
threshold = 40
style = "italic #ffbf00"

[[battery.display]]
threshold = 50
style = "italic #95ff00"

[[battery.display]]
threshold = 60
style = "italic #95ff00"

[[battery.display]]
threshold = 70
style = "italic #3cff00"

[[battery.display]]
threshold = 80
style = "italic #3cff00"

[[battery.display]]
threshold = 90
style = "italic #00ff33"

[[battery.display]]
threshold = 100
style = "italic #00ff33"


[time]
disabled = false
format = "[ $time]($style)"
time_format = "%r"
utc_time_offset = "local"
style = "italic #00bfff"


[cmd_duration]
min_time = 0
format = "[  $duration ](italic #96f8ff)"

[character]
format = "$symbol "
success_symbol = "[ ](bold italic #00ff08)"
error_symbol = "[ ](italic #ff8c00)"
vimcmd_symbol = "[■](italic dimmed green)"

[sudo]
format = "[$symbol]($style)"
style = "bold #ff0077"
symbol = "  "
disabled = false

